### ISSUE TITLE
ERROR: 'utf-8' codec can't decode byte 0xe7 in position 3: invalid continuation byte

### ISSUE THREAD

**Issue by andreas-it-dev** [avallete/lockwise-password-importer#1]
the extractor throws an error when trying to extract my chrome pws

```
python3 chrome_login_database_extractor.py -o ./outfile.csv
INFO: Login Data found on here: /home/andreas/.config/google-chrome/Default
Do you want to extract passwords from this file ?:  [y/N]: y
INFO: Try to connect to /home/andreas/.config/google-chrome/Default/Login Data database
INFO: Connected successfully to database, 1850 passwords found
ERROR: 'utf-8' codec can't decode byte 0xe7 in position 3: invalid continuation byte
```

**Comment by avallete** [comment]
Hi,

Look like an charset error, due to non utf-8 character.

What is the result on your system if you open a python console and type:

```
import sys
sys.getdefaultencoding()
```

I will try to test the script with some non-utf8 passwords as well to see if I can reproduce the bug on my system.

**Comment by andreas-it-dev** [comment]
Hi Andrew,

i get utf-8

```
[andreas@world-hq ~]$ python
Python 3.7.4 (default, Oct  4 2019, 06:57:26) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.getdefaultencoding()
'utf-8'
>>> 
```

**Comment by avallete** [comment]
Investigating this issue, it seem that chrome passwords are sometimes encrypted, and that may be the reason why decoding it as 'utf-8' directly fail.

Strange thing is that during my tests, I didn't experienced this issue at all even with one of the latest chromium version :thinking: 

I've made some change on this branch: https://github.com/avallete/lockwise-password-importer/tree/fix-linux-chrome-export

Could you please try the extraction with this version of the code and tell me if it fix your issue on linux ?

PS: this branch need a new crypto lib as requirement, so think about `pip install -r requirements.txt`

**Comment by andreas-it-dev** [comment]
thx for taking a look at this, Andrew..

however, this has not brough us a whole lot further.. it starts to extract but then quickly throws (proly the unencrypted pws) as error

```
[andreas@world-hq lockwise-password-importer-fix-linux-chrome-export]$ python3 chrome_login_database_extractor.py -o ./outfile.csv
INFO: Login Data found on here: /home/andreas/.config/google-chrome/Default [l.99]
Do you want to extract passwords from this file ?:  [y/N]: y
INFO: Try to connect to /home/andreas/.config/google-chrome/Default/Login Data database [l.118]
INFO: Connected successfully to database, 1850 passwords found [l.123]
ERROR: with data for [https://example.com/]: 'utf-8' codec can't decode byte 0xfd in position 0: invalid start byte [l.157]
ERROR: with data for [http://www.example.net/]: 'utf-8' codec can't decode byte 0xce in position 1: invalid continuation byte [l.157]
INFO: Passwords saved into: /tmp/lockwise-password-importer-fix-linux-chrome-export/outfile.csv [l.167]
```
and those encrypted (i suppose) are empty:

```
"hostname","formSubmitURL","usernameField","passwordField","username","password"
"https://url.one/","","","","",""
"https://url2.net/","","","","",""
```

**Comment by avallete** [comment]
Hi, thanks for your quick response.

Look like Chrome have different ways of saving passwords depending of your system and the way the process is launched (with the --password-store argument) which either make it use system keyring to store the password master encryption key or 'peanuts' as default encryption key.

I've added some more modification on the branch I've mentioned earlier to automatically make the script connect to 'secretstorage' module if it's available and automatically search for chrome/chromium master keys.

Could you please give it a shot again ?

**Comment by andreas-it-dev** [comment]
that did the trick, great job Andrew!

```
andreas@world-hq lockwise-password-importer-fix-linux-chrome-export]$ python3 chrome_login_database_extractor.py -o ./outfile.csv
INFO: Login Data found on here: /home/andreas/.config/google-chrome/Default [l.119]
Do you want to extract passwords from this file ?:  [y/N]: y
INFO: Try to connect to /home/andreas/.config/google-chrome/Default/Login Data database [l.138]
INFO: Connected successfully to database, 1850 passwords found [l.143]
INFO: Decryption key found in secretstorage under: Chrome Safe Storage [l.47]
Do you want to use this key to decrypt your passwords ?:  [y/N]: y
INFO: Passwords saved into: /tmp/lockwise-password-importer-fix-linux-chrome-export/outfile.csv [l.187]

```

thanks alot,
Andreas
