### ISSUE TITLE
importer unspecified error [l.196]

### ISSUE THREAD

**Issue by luis-pereira** [avallete/lockwise-password-importer#4]
```
(venv) [lpereira@l-pc lockwise-password-importer]$ python3 lockwise_password_importer.py ~/Documents/xpto.csv 
Email: XXXXXXXXXXXXXXX
Password: 
206 passwords will be loaded into firefox, do you confirm ?  [y/N]: y
ERROR: Unspecified error [l.196]
```
I'm available to provide more info, if told how.

**Comment by avallete** [comment]
Hi @luis-pereira,

Thank's for opening the issue. Could you tell me which OS you use (Linux || OSX) ?

Also, could you try to rerun the script changing this line:

https://github.com/avallete/lockwise-password-importer/blob/0c0bdcba80f7001fd8daffcf90c312241dd1da41/lockwise_password_importer.py#L24

for:
```python3
logging.basicConfig(format='%(levelname)s: %(message)s [l.%(lineno)d]', level=logging.DEBUG)
```

And copy/paste the new output.

PS: Be sure to remove all sensitive data who may be leaked by the DEBUG level of the logs.

**Comment by luis-pereira** [comment]
@avallete I'm using Linux (Manjaro).
I did the change you suggested and by magic it worked. Under the same exact conditions.
After a long long debug info, it ended with:
It ended with:|
```
DEBUG: Synced password records: 201 [l.167]
INFO: Done! [l.168]
```

**Comment by avallete** [comment]
Strange, it was probably an unexpected error related to the login. Maybe a network issue has resolved in the main time.

I close this issue for now, if anyone encounter the same problem again, please fell free to reopen.
